### ISSUE TITLE
cap2 - correção ortográfica

### ISSUE THREAD

**Issue by sylviosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#37]
Versão do livro: `v1.0.0`
Página: 35
Na frase anterior a Seção 2.8.2 "Aqueles computadores que lideram a lista do Top 500, e são capazes até de mudar o PIB de um país, trabalham na escala do TFLOPS (Teta FLOPS)." a unidade TFLOPS está grafada como Teta FLOPS. Não seria Tera FLOPS?

**Comment by edusantana** [comment]
Realmente @sylviosoares
Realizei a correção, mas vou aguardar até a próxima semana para gerar uma nova versão, juntando outras correções que vocês venham a encontrar.
