### ISSUE TITLE
Correção ortográfica

### ISSUE THREAD

**Issue by sylviosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#38]
Seção 3.2.1 Busca de Instrução

No trecho "A instrução precisa sempre estar em IR porque na faze de decodificarão, a Unidade de Controle vai buscar lá que instrução deve executar." o termo "faze de decodificarão" deve ser "fase de decodificação".

**Comment by edusantana** [comment]
Obrigado @sylviosoares correção realizada.
