### ISSUE TITLE
Cap3: Correção ortográfica

### ISSUE THREAD

**Issue by sylviosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#39]
3.4 Decodificação

No trecho "O primeiro da decodificarão é ler o código da instrução para conhecer seu tipo." acredito estar faltando uma palavra entre "primeiro" e "da" (passo ou etapa?) e a palavra decodificação está escrita "decodificarão".

**Comment by edusantana** [comment]
Oi @sylviosoares gerei uma nova versão do livro com suas alterações:
https://github.com/ufpb-computacao/introducao-a-arquitetura-de-computadores-livro/releases/tag/v1.5.6
