### ISSUE TITLE
Correções ortográficas

### ISSUE THREAD

**Issue by sylviosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#41]
Na seção 5.4.3 no 2º parágrafo abaixo da figura 5.3 a palavra "refrescagem" está escrita "refrescarem".

Item 5.5 na definição de SSD está escrita "mais residente" ou deveria ser "mais resistente".

Item 5.7.1 A redação da 2º frase do parágrafo está estranha... "Geralmente há a Memória Cache de um computador é 1.000 vezes menor do que a Memória Principal.

**Comment by edusantana** [comment]
Oi @sylviosoares obrigado por suas contribuições, elas são bastante valiosas.

**OBS:** como você pode ver em 172f448d5d0fcb3baf37df226e1b626553fca8c9 havia outro erro com `refrescarem`.
