### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#42]
Versão do livro: Ed. v1.5.6
Página: 4

Onde está escrito "...Por exemplo, quando uma instrução pede que uma mensagem SEM impressa na tela, a CPU, ao receber e executar essa instrução, envia para o controle do monitor que imprimA na tela a mensagem contida O endereço que também foi passada pela instrução..."

o correto seria "...Por exemplo, quando uma instrução pede que uma mensagem SEJA impressa na tela, a CPU, ao receber e executar essa instrução, envia para o controle do monitor que imprimE na tela a mensagem contida NO endereço que também foi passada pela instrução..."

**Comment by edusantana** [comment]
Oi @glaucosoares 

Obrigado pelas contribuições, como foram dois erros simples de digitação, não vou gerar outra versão por enquanto, caso você encontre mais, eu gero, ok?

Mas com certeza, na próxima versão impressa eles sairão corrigidos.
