### ISSUE TITLE
cap1 Erro de digitação

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#43]
Versão do livro: v1.5.6
Página: 12

Na sessão 1.8.3 onde está escrito: "..Não preciso nem dizer o QUE isso era trabalhoso"

deveria ser: ""..Não preciso nem dizer o QUANTO isso era trabalhoso"

**Comment by edusantana** [comment]
Obrigado @glaucosoares a correção foi realizada. Agendei a geração de uma nova release do livro em 11 de setembro, que conterá todas essas correções e demais que venham a ser notificadas.

**Comment by edusantana** [comment]
@glaucosoares gerei uma nova versão do livro, contendo esses e outras correções. Você pode baixá-la em  [links-para-baixar-os-livros.txt](https://github.com/edusantana/guia-geral-ead-computacao-ufpb/blob/master/livro/capitulos/links-para-baixar-os-livros.txt)
