### ISSUE TITLE
cap2 [Erro de digitação]

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#44]
Versão do livro: v1.5.7
Página: 33

Na sessão 2.8.2 onde está escrito: "Suponha que um programa eéxecutado..."

deveria ser: "Suponha que um programa é executado..."

**Comment by edusantana** [comment]
Oi @glaucosoares realmente, acho que deve ser erro de codificação do arquivo, pois [o arquivo original não possui o erro](https://raw.githubusercontent.com/ufpb-computacao/introducao-a-arquitetura-de-computadores-livro/master/livro/capitulos/2_CPU.asc). Rastreei o erro desde a versão [v0.3.0](https://github.com/ufpb-computacao/introducao-a-arquitetura-de-computadores-livro/releases/download/v0.3.0/introducao-a-arquitetura-de-computadores-livro-v0.3.0.pdf).

Depois vou analisar melhor.

**Comment by edusantana** [comment]
O erro foi decorrente da confusão de caracteres e codificação entre `é` e `é`. O texto original estava codificado com `é`, que causou problema na codificação e geração do arquivo. O problema não era perceptível visualmente no editor de texto, apenas no pdf gerado.
