### ISSUE TITLE
cap3 - correção ortográfica

### ISSUE THREAD

**Issue by glaucosoares** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#45]
Versão do livro: v1.5.7
Página: 38

Na sessão 3.2.1 onde está escrito: "A instrução precisa sempre estar em IR porque na fase de decodificarão..."

deveria ser: "A instrução precisa sempre estar em IR porque na fase de decodificação"

**Comment by edusantana** [comment]
Obrigado @glaucosoares a correção sairá na próxima release. Agendei a geração de uma nova release para o dia _23 de Outubro_, caso você ou seu colegas submetam novas correções iremos incorporá-las na próxima release.

**Comment by edusantana** [comment]
Oi @glaucosoares gerei uma [nova versão do livro com as correções indicadas](https://github.com/ufpb-computacao/introducao-a-arquitetura-de-computadores-livro/releases/tag/v1.5.8).

Obrigado pelas contribuições!
