### ISSUE TITLE
Confusão em uma frase

### ISSUE THREAD

**Issue by gutierri** [ufpb-computacao/introducao-a-arquitetura-de-computadores-livro#47]
No primeiro capítulo, logo no primeiro paragrafo das [**Operações Básicas** ](https://github.com/ufpb-computacao/introducao-a-arquitetura-de-computadores-livro/blob/master/livro/capitulos/1_introducao.asc#opera%C3%A7%C3%B5es-b%C3%A1sicas) tem uma frase que causa uma certa confusão.

> A movimentação de dados é a transferência **de um dado de um ponto** para outro do computador.

Está certo?

**Comment by edusantana** [comment]
Olá @gutierri , primeiramente obrigado por sua contribuição anterior. A correção será incorporada na próxima versão do livro.

Agora, sobre essa passagem, gostaria de compreender sua percepção sobre ela. Lendo assim, acho que _de um dado de um ponto_ está parecido com a expressão talvez comum na matemática _de um dado ponto_.

Para mim ficaria mais claro trocando a palavra ~~ponto~~ por  **lugar**, então ficaria:

> A movimentação de dados é a transferência de um dado de um _lugar_ para outro do computador.

Mas não estou certo se era isso a que você estava se referindo. Você poderia explicar melhor seu ponto de vista, e talvez uma provável solução para que possamos compreender melhor?

**Comment by gutierri** [comment]
Para mim pareceu um pouco confuso, mas talvez seja por falta de conhecimento em relação a termos matemáticos.

Acho que podemos fechar a "issue".
